In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype=np.int32)
print(a.dtype)

int32


In [3]:
b = np.array([1,2,3],dtype=np.float)
print(b.dtype)

float64


In [4]:
c = np.array([1,2,3])#一维数组
print(c)

[1 2 3]


In [5]:
d = np.array([[1,2,3],   #2维矩阵
                      [4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [6]:
zero = np.zeros((2,3)) #生成2行3列全为0的矩阵
print(zero)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [7]:
one = np.ones((3,4)) #生成3行4列全为1的矩阵
print(one)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [8]:
empty = np.empty((3,2))#生成3行2列全都接近于0（不等于0）的矩阵
print(empty)

[[  6.75727706e-057   8.27486518e+010]
 [  4.46701125e+020   3.52144182e+030]
 [  1.28478738e-311   1.28477706e-311]]


In [9]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
f = np.arange(4,12)
print(f)

[ 4  5  6  7  8  9 10 11]


In [11]:
g = np.arange(1,20,3)
print(g)

[ 1  4  7 10 13 16 19]


In [12]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
h = np.arange(8).reshape(4,2)#重新定义矩阵的形状
print(h)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
