In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],
                           [4,5,6]])
arr2 = np.array([[1,1,2],
                           [2,3,3]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 1 2]
 [2 3 3]]


In [3]:
print(arr1 + arr2)

[[2 3 5]
 [6 8 9]]


In [4]:
print(arr1 - arr2)

[[0 1 1]
 [2 2 3]]


In [5]:
print(arr1 * arr2)

[[ 1  2  6]
 [ 8 15 18]]


In [6]:
print(arr1 ** arr2)

[[  1   2   9]
 [ 16 125 216]]


In [7]:
print(arr1 / arr2)

[[ 1.          2.          1.5       ]
 [ 2.          1.66666667  2.        ]]


In [8]:
print(arr1 % arr2)

[[0 0 1]
 [0 2 0]]


In [9]:
print(arr1 // arr2)

[[1 2 1]
 [2 1 2]]


In [10]:
print(arr1+2)#所有的元素加2

[[3 4 5]
 [6 7 8]]


In [11]:
print(arr1*10)#所有的元素乘以10

[[10 20 30]
 [40 50 60]]


In [12]:
arr3 = arr1 > 3 #判断哪些元素大于3
print(arr3)

[[False False False]
 [ True  True  True]]


In [13]:
arr4 = np.ones((3,5))
print(arr4) 

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [14]:
print(arr1)        

[[1 2 3]
 [4 5 6]]


In [15]:
np.dot(arr1,arr4)#矩阵乘法   2*3  3*5

array([[  6.,   6.,   6.,   6.,   6.],
       [ 15.,  15.,  15.,  15.,  15.]])

In [16]:
arr1.dot(arr4)#矩阵乘法

array([[  6.,   6.,   6.,   6.,   6.],
       [ 15.,  15.,  15.,  15.,  15.]])

In [17]:
print(arr1)
print(arr1.T)#矩阵转置
print(np.transpose(arr1))#矩阵转置

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
