In [1]:
import numpy as np

In [7]:
sample1 = np.random.random((3,2))#生成3行2列从0到1的随机数
print(sample1)

[[ 0.42771704  0.0186182 ]
 [ 0.26530316  0.5394374 ]
 [ 0.90250021  0.4787342 ]]


In [9]:
sample2 = np.random.normal(size=(3,2))#生成3行2列符合标准正态分布的随机数
print(sample2)

[[-0.58502901  0.84828283]
 [-0.45145387 -0.60442302]
 [-0.36218717  0.03578238]]


In [12]:
sample3 = np.random.randint(0,10,size=(3,2))#生成3行2列从0到10的随机整数
print(sample3)

[[6 2]
 [8 7]
 [0 3]]


In [13]:
print(sample1)

[[ 0.42771704  0.0186182 ]
 [ 0.26530316  0.5394374 ]
 [ 0.90250021  0.4787342 ]]


In [14]:
np.sum(sample1)#求和

2.6323102019658302

In [15]:
np.min(sample1)#求最小值

0.018618197949608173

In [16]:
np.max(sample1)#求最大值

0.9025002056189162

In [17]:
np.sum(sample1,axis=0)#对列求和

array([ 1.59552041,  1.03678979])

In [18]:
np.sum(sample1,axis=1)#对行求和

array([ 0.44633524,  0.80474056,  1.3812344 ])

In [19]:
np.argmin(sample1)#求最小值的索引

1

In [20]:
np.argmax(sample1)#求最大值的索引

4

In [21]:
print(np.mean(sample1))#求平均值
print(sample1.mean())#求平均值

0.438718366994
0.438718366994


In [22]:
np.median(sample1)#求中位数

0.45322562055195098

In [23]:
np.sqrt(sample1)#开方

array([[ 0.6540008 ,  0.13644852],
       [ 0.51507588,  0.73446402],
       [ 0.95000011,  0.69190621]])

In [24]:
sample4 = np.random.randint(0,10,size=(1,10))
print(sample4)

[[8 1 3 1 2 4 8 9 4 7]]


In [28]:
np.sort(sample4)#排序

array([[1, 1, 2, 3, 4, 4, 7, 8, 8, 9]])

In [26]:
np.sort(sample1)

array([[ 0.0186182 ,  0.42771704],
       [ 0.26530316,  0.5394374 ],
       [ 0.4787342 ,  0.90250021]])

In [29]:
np.clip(sample4,2,7)#小于2就变成2，大于7就变为7

array([[7, 2, 3, 2, 2, 4, 7, 7, 4, 7]])